// Code generated by cmd/generate-tcp16_20

package tcp16_20_generated

import (
	"prikop/internal/verifier/types"
)

func Cases() []types.ProviderDefinition {
	return []types.ProviderDefinition{
		{
			Name:       "aws",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/aws/aws_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://www.getscope.com/assets/fonts/fa-solid-900.woff2", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://corp.kaltura.com/wp-content/cache/min/1/wp-content/themes/airfleet/dist/styles/theme.css", Threshold: 596179, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "akamai",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/akamai/akamai_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://media.miele.com/images/2000015/200001503/20000150334.png", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://www.roxio.com/static/roxio/videos/products/nxt9/lamp-magic.mp4", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "cdn77",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/cdn77/cdn77_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://cdn.eso.org/images/banner1920/eso2520a.jpg", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "cloudflare",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/cloudflare/cloudflare_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://www.bigcartel.com/_next/static/chunks/453-03e77cda85f8a09a.js", Threshold: 210116, Proto: types.ProtoTCP},
				{URL: "https://aegis.audioeye.com/assets/index.js", Threshold: 218884, Proto: types.ProtoTCP},
				{URL: "https://img.wzstats.gg/cleaver/gunFullDisplay", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://esm.sh/gh/esm-dev/esm.sh@e7447dea04/server/embed/assets/sceenshot-deno-types.png", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "contabo",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/contabo/contabo_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://www.cateringexner.cz/font/ebrima/ebrima.woff2", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://findair.net/wp-content/uploads/2025/07/online-booking-2.jpeg", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "digitalocean",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/digitalocean/digitalocean_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://carishealthcare.com/content/uploads/2025/04/Rectangle-105.jpg", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://bohnlawllc.com/wp-content/uploads/sites/27/2024/01/Trusts.jpg", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://ecomstal.com/_next/static/css/73cc557714b4846b.css", Threshold: 443944, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "fastly",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/fastly/fastly_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://ssl.p.jwpcdn.com/player/v/8.40.5/bidding.js", Threshold: 250078, Proto: types.ProtoTCP},
				{URL: "https://www.jetblue.com/footer/footer-element-es2015.js", Threshold: 215899, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "gcore",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/gcore/gcore_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://gcore.com/assets/fonts/Montserrat-Variable.woff2", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "googlecloud",
			CIDRSource: "https://www.gstatic.com/ipranges/cloud.json",
			Targets: []types.Target{
				{URL: "https://api.usercentrics.eu/gvl/v3/en.json", Threshold: 521495, Proto: types.ProtoTCP},
				{URL: "https://widgets.reputation.com/fonts/Inter-Light.ttf", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "hetzner",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/hetzner/hetzner_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://apiwhatsapp-1000.zapipro.com/libs/bootstrap/dist/css/bootstrap.min.css", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://www.industrialport.net/wp-content/uploads/custom-fonts/2022/10/Lato-Bold.ttf", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://251b5cd9.nip.io/1MB.bin", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://nioges.com/libs/fontawesome/webfonts/fa-solid-900.woff2", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://5fd8bdae.nip.io/1MB.bin", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://5fd8bca5.nip.io/1MB.bin", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "melbicom",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/melbicom/melbicom_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://twin.mentat.su/assets/fonts/Inter-SemiBold.woff2", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "ovh",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/ovh/ovh_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://app.symarobot.com/content/images/logo.png", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://filmoteka.net.pl/css/bootstrap.min.css", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "oracle",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/oracle/oracle_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://global-seres.com.sg/wp-content/uploads/2024/02/SVG00732-scaled.jpg", Threshold: 65536, Proto: types.ProtoTCP},
				{URL: "https://zojirushi.sg/wp-content/uploads/2026/02/SU-BA48.png", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "scaleway",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/scaleway/scaleway_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://www.velivole.fr/img/header.jpg", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
		{
			Name:       "vultr",
			CIDRSource: "https://raw.githubusercontent.com/123jjck/cdn-ip-ranges/refs/heads/main/vultr/vultr_plain_ipv4.txt",
			Targets: []types.Target{
				{URL: "https://static-cdn.play.date/static/js/model-viewer.min.js", Threshold: 226114, Proto: types.ProtoTCP},
				{URL: "https://us.rudder.qntmnet.com/QN-CDN/images/qn_bg_.jpg", Threshold: 65536, Proto: types.ProtoTCP},
			},
		},
	}
}
